apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: monitoring
  labels:
    app: gatus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
